spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test
    username: tkang
    password: 12345678
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    defer-datasource-initialization: true
    hibernate.ddl-auto: update
    properties:
      hibernate.format_sql: true
      hibernate.show_sql: true
      hibernate.default_batch_fetch_size: 100
